export const Options = [
  "Technology News",
  "Programming",
  "Internet of Things",
  "Tech Reviews",
  "Software Development",
  "Adobe Illustrator",
  "Adobe Photoshop",
  "Backgrounds",
  "Textures",
  "Patterns",
  "Vector",
  "Drawing",
  "Clip Art",
  "Silhouettes",
  "Cartoons",
  "Symbols and Signs",
  "Social Media",
  "Business Cards",
  "Greeting Cards",
  "Invitations Cards",
  "Banners",
  "Flyers",
  "Posters",
  "Stationery",
  "Logos",
  "Mockups",
  "Typography Font",
  "Photo Editing",
  "Lightroom",
  "Video Editing",
  "Ethical Hacking",
  "Photos",
  "Web Design and Development",
  "Digital Marketing",
  "Auto Cad",
  "Office Applications",
  "Database Programming",
  "Data Entry",
  "Class",
  "Projects",
  "Plugin",
  "Music",
  "Movies",
  "Writing Blog",
  "My Data",
  "Our Course",
  "Notice",
  "Graphics Design",
  "Motions Graphics",
  "Python Programming",
];
