export const WorkData = [
  "Vector Illustration",
  "Swimming Pool Design",
  "Cyberpunk Art",
  "Political Cartoon",
  "Cyberpunk Logo",
  "Robot Design",
  "Gundam",
  "Fantasy Horror Character",
  "Game Characters",
  "Logo Design",
  "Brand Style Guides",
  "Fonts & Typography",
  "Business Cards",
  "Book Cover Design",
  "Botanical Illustration",
  "Fantasy Art",
  "Anime Character",
  "Comic Character",
  "Superhero Comic",
  "Political Cartoon",
  "DND Character Art",
  "Watercolor Painting",
  "Pin Up Girl",
  "Game Character",
  "Concept Art",
  "Oil Painting",
  "Album Cover Design",
  "Children Book Cover",
  "Illustration",
  "Portraits & Caricatures",
  "Cartoons & Comics",
  "Tattoo Design",
  "Food Pop Art",
  "Family Portrait",
  "Car Portrait",
  "Anime Portrait",
  "Coffee Mug Design",
  "Anime Character Pop Art",
  "Children Comic",
  "Superhero Character",
  "Couple Portrait",
  "Vector Portrait",
  "Fashion Design",
  "Fantasy Horror Character",
  "Children Book Illustration",
  "Abstract Art",
  "Manga Character",
  "Car Warp",
];
