export const Paragraphs: string[] = [
  "A plant is one of the most important living things that develop on the earth and is made up of stems, leaves, roots, and so on. Parts of Plants: The part of the plant that developed beneath the soil is referred to as root and the part that grows outside of the soil is known as shoot. The shoot consists of stems, branches, l eaves, fruits, and flowers. Plants are made up of six main parts: roots, stemleaves, flowers, fruits, and seeds.",

  "The root is the part of the plant that grows in the soil. The primary root emerges from the embryo. Its primary function is to provide the plant stability in the earth and make other mineral salts from the earth available to the plant for variometabolic processes There are three types of roots i.e. Tap Root, Adventitious Roots, aLateral Root. The roots arise from the parts of the plant and not from the rhizomes roots.",

  "Stem is the posterior part that remains above the ground and grows negatively geotropic. Internodes and nodes are found on the stem. Branch, bud, leaf, petiole, flower, and inflorescence on a node are all those parts of the plant that remain above tground and undergo negative subsoil development. The trees have brown bark and the youand newly developed stems are green. The roots arise from the parts of plant and nfrom the rhizomes roots.",

  "It is the blossom of a plant. A flower is the part of a plant that produces seeds, which eventually become other flowers. They are the reproductive system of a plant. Most flowers consist of 04 main parts that are sepals, petals, stamens, and carpels. The female portion of the flower is the carpels. The majority of flowers ahermaphrodites, meaning they have both male and female components. Others may consist of one of tparts and may be male or female.",
  "An aunt is a bassoon from the right perspective. As far as we can estimate, some posit the melic myanmar to be less than kutcha. One cannot separate foods from blowbows. The scampish closet reveals itself as a sclerous llama to those who look. A hip the skirt of a peak. Some hempy laundries are thought of simply as orchids. A gum is a trumpet from the right perspective. A freebie flight is a wrench of the mind. Some posit the croupy.",

  "In this enchanted realm, the symphony of innovation echoed through the corridors of imagination, and the keyboard became a wand, casting spells of logic and creativity. The saga of this digital odyssey, unbound by the constraints of the tangible world, continued to evolve, a testament to the ever-expanding horizons of technology. unbound by the constraints of the tangible world, continued to evolve, a testament to the ever-expanding horizons of technology",

  "As the sun dipped below the horizon, painting the sky in hues of orange and pink, a gentle breeze rustled the leaves of the ancient oak trees. In the meadow, wildflowers swayed in rhythm with nature's melody. A babbling brook meandered through the landscape, reflecting the fading sunlight. Far in the distance, the silhouette of a mountain stood proudly against the twilight sky. Nature's symphony played on, inviting those who paused to listen to the harmonious convergence of elements, a timeless dance of light and shadow.",

  "In the quietude of the moonlit night, shadows danced across the ancient walls of the castle. The air was filled with a mysterious stillness, broken only by the distant howl of a lone wolf. Within the castle's chambers, forgotten whispers of the past lingered, telling tales of bygone eras. A flickering candle cast ephemeral light, revealing weathered books and forgotten artifacts. Unbeknownst to the world outside, the castle held secrets etched in the stones, waiting to be unraveled by those daring enough to explore its silent corridors and unlock the mysteries of time.",

  "Underneath the city lights, a bustling metropolis came alive with the pulse of urban energy. Skyscrapers reached towards the heavens, their glass facades reflecting the vibrant spirit of the city. Streets buzzed with a kaleidoscope of colors as people hurried about, each with their own destination and story to tell. Nature's symphony played on, inviting those who paused to listen to the harmonious convergence of elements, a timeless dance of light and shadow",
];
